### ISSUE TITLE
Trace Server Server error messages should be handled gracefully

### ISSUE THREAD

**Issue by MatthewKhouzam** [theia-ide/theia-trace-extension#234]
If a server crashes (e.g. vm goes down) the front end should handle it gracefully and inform the user of the issue.

**Comment by marechal-p** [comment]
I was about to open a similar issue: I tried running the trace server from the status bar nothing happened but had the following trace in the logs:

```
root ERROR Uncaught Exception:  Error: spawn ../trace-compass-server/tracecompass-server ENOENT
root ERROR Error: spawn ../trace-compass-server/tracecompass-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
root ERROR [hosted-plugin: 4299] Promise rejection not handled in one second: undefined , reason: undefined
```

In this case I forgot to pull the trace server jar, but showing something in the UI could help?

**Comment by mirsky-work** [comment]
@marechal-p, #226 adds a toast message in that scenario.

**Comment by ebugden** [comment]
I'm un-assigning myself because I won't be working on this in the immediate future. @MatthewKhouzam Thanks for mentioning this important issue!
